# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template that deploys web-app
Parameters:
  ServiceName:
    Type: String
    Default: crazy-fun-web
    Description: Crazy fun web.
Resources:
  Service:
    Metadata:
      'aws:apprunner:description': 'crazy fun web service'
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref ServiceName
      SourceConfiguration:
        AutoDeploymentsEnabled: false
        ImageRepository:
          ImageIdentifier: public.ecr.aws/aws-containers/crazy-fun-web:latest
          ImageRepositoryType: ECR_PUBLIC
          ImageConfiguration:
            Port: 8000
Outputs:
  Endpoint:
    Description: "The endpoint of the App Runner service."
    Value: !GetAtt Service.ServiceUrl
